### PR TITLE
Raw string integers to integers list

### PR DESCRIPTION
**Pull request by goutham2027**
Returns integers list when inputted with string of integers.

### CODE REVIEW

**Comment by st0le** [comment]
map(int, input().split())

**Comment by NamPNQ** [comment]
@goutham2027 like @st0le is better

**Comment by brennerm** [comment]
I agree with @st0le's way as well.

**Comment by goutham2027** [comment]
Even I like @st0le's  way.

**Comment by brennerm** [comment]
Would you like to change it in your code ? :)
And please don't ask for user input. Just assign a string and use it.

**Comment by goutham2027** [comment]
Updated.

**Pull request closed without merging**
