### PR TITLE
add two tricks

### PR DESCRIPTION
**Pull request by illuz**
Added setglobalvariables.py and removeduplicatefromlist.py.

### CODE REVIEW

**Comment by brennerm** [comment]
Want to add yourself to the contributors?

**Comment by illuz** [comment]
Yes. :-)

**Comment by brennerm** [comment]
Then please do so ;)

**Comment by illuz** [comment]
But excuse me, I don't know how to do it.

**Comment by brennerm** [comment]
Try to add another commit to this pull request :)
Have a look at [this](http://stackoverflow.com/questions/7947322/preferred-github-workflow-for-updating-a-pull-request-after-code-review)

**Pull request merged**
