### PR TITLE
string of integers to integers list using map

### PR DESCRIPTION
**Pull request by goutham2027**

### CODE REVIEW

**Comment by brennerm** [comment]
The current output when using Python3 is

```
### Input ###
1 2 3 4 5 6
### Output ###
<map object at 0x1103f2d68>
```

Please convert the iterator to a list by changing this line:

``` python
print(list(int_input))
```

**Comment by brennerm** [comment]
And be sure to add yourself to the contributors ;)

**Comment by goutham2027** [comment]
Updated.

**Comment by brennerm** [comment]
Thanks! :)

**Pull request merged**
