### PR TITLE
Python allows a convenient else clause for while.

### PR DESCRIPTION
**Pull request by cgopalan**

### CODE REVIEW

**Comment by brennerm** [comment]
Can you please show off somehow, that the else clause is not executed when the while loop exits with a break?

**Comment by cgopalan** [comment]
Updated. If you execute it, it will print:
Whiling away!
Whiling away!
which means the else clause was not executed.

**Comment by brennerm** [comment]
Thanks!
Wanna add yourself to the contributors?

**Comment by cgopalan** [comment]
Thanks! This is a cool list.

**Comment by brennerm** [comment]
Thanks, didn't expect it to become that big :)

**Pull request merged**
