### PR TITLE
Creating a basic type of categorization

### PR DESCRIPTION
**Pull request by felipevolpone**
Hey guys, I just create a basic type of separation in the README.md and created some folders to add the snippets that belong to these subjects. If you agree with this way, I'll continue.
Tks

### CODE REVIEW

**Comment by brennerm** [comment]
@felipevolpone, thanks for your proposal. I really like it so far. Here are some notes from my site:
- what would you categorize under "The Python Model Object"?
- please remove all files, that don't belong to the categorization from this PR
- to what location will the entries link to?
- please add a "Others" section, cause some examples don't fit any category

**Comment by felipevolpone** [comment]
Hey @brennerm, answering your questions:

1) I would put files that involve use of the dunder methods of Python. (http://www.rafekettler.com/magicmethods.html, https://docs.python.org/2/reference/datamodel.html). I'm not sure that we've some snippet to this item.

2) OK

3) The links could send to the folder of that item. What do you think?

4) OK

**Comment by brennerm** [comment]
1) I can't find an example for now, but I agree with your opinion.
3) Agree :+1:

**Comment by brennerm** [comment]
Would you like to create the folders and move all files or shall I take care of this?

**Comment by felipevolpone** [comment]
I can do this, no problem.

**Comment by brennerm** [comment]
Thank you :)

**Comment by felipevolpone** [comment]
hey @brennerm, sorry for the delay. I'll do a pull request very soon.

**Comment by felipevolpone** [comment]
@brennerm verify what I did. I changed a little of my first proposal, but I think it's better now.

**Comment by brennerm** [comment]
Nice!
What do you think about linking directly to the file?

**Comment by felipevolpone** [comment]
Sounds great, but some categories have more than just one file to link. What do you suggest?

**Comment by brennerm** [comment]
Yeah you're right. We can leave it as is.

**Pull request closed without merging**
