### PR TITLE
Adds an example of using python's lazy or

### PR DESCRIPTION
**Pull request by dcbaker**
This example touches on two different things, first, the problem of
using mutable objects and default keyword values, and second an
interesting trick to side step them.

This might deserve two separate examples, since it conflates two things that aren't necessarily related.

### CODE REVIEW

**Comment by brennerm** [comment]
Hey I see your point. I would like to add it to conditionalassignment.py, instead of creating a new file.
Please enlighten me, if I understand your example wrong ;).

**Comment by dcbaker** [comment]
Adding it to conditionalassignemnt.py probably makes sense. I wrote this against a fairly old checkout of the repository (a couple of days), so there was not conditionalassignment.py at the time. I'll update the pull request

**Comment by brennerm** [comment]
Thanks, be sure to add yourself to the contributors :)

**Comment by brennerm** [comment]
Oh you already had :D

**Pull request merged**
