### PR TITLE
Add setinitialvalue.py

### PR DESCRIPTION
**Pull request by rickhau**
Add a pythonic way to set initial value

### CODE REVIEW

**Comment by brennerm** [comment]
I would like to add this to https://github.com/brennerm/PyTricks/blob/master/conditionalassignment.py , cause the example is basically based on conditional assignment. Do you agree with this?

**Comment by rickhau** [comment]
Yes, I agree. So, will you add my example used by function call into that file? Just to confirm if I need to send another pull request for the update or close this pull request. Thanks.

**Comment by brennerm** [comment]
Yes I'm going to add it. You are already in the contributors file if I remember correctly, right?

**Comment by brennerm** [comment]
Just came into my mind. Why not just use:

``` python
def setDefaultNew(initial=60):
    return initial
```

?
Is there any benefit doing it your way?

**Comment by rickhau** [comment]
If you accidentally pass a None or False value, it will return without check. initial = initial or 60 can do the check for you in case any unexpected value being passed.

**Comment by brennerm** [comment]
Yeah that's right. I'll add it.

**Comment by rickhau** [comment]
Thanks. That is also part of the reason why I used function instead of showing only one line. The example is mainly to show when we want to add a check on the passing arguments before we use them in the function body.

**Pull request closed without merging**
